url: ''
baseurl: ''
title: 'Kian Pak'

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  projects:
    output: true,

defaults:
  - scope:
      type: posts
      path: _posts
    values:
      layout: prose
  - scope:
      type: projects
      path: _projects
    values:
      layout: prose

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
